### ISSUE TITLE
Create and store target language code folders

### ISSUE THREAD

**Issue by miurla** [Cs4K1Sr4C/AutoTranslator-i18n#1]
Currently, the translated files are stored in the translation folder, but since you are entering the target language code, it would be useful if you could create and store folders for each language. This would also prevent unnecessary files in the translation folder from being committed.

Please consider it!

**Comment by Cs4K1Sr4C** [comment]
Thank you for your feedback and suggestion about this point. I'll make the corresponding changes!

 I'll implement this under the functionality of "Determine the allowed locales of the project" and I'll create an entry point which will be available using the `npm run translate-all-available --srcLang` to translate the entire project automatically and this for sure needs this kind of folder separation inside of the translation directory.

Also I'm thinking on that, on single translation maybe better to create the target language's directory if it's not exist directly in the locales folder. If it's an existing directory then ATi18n will create a a translation folder inside the target language's directory to avoid the overwrites...

**Comment by Cs4K1Sr4C** [comment]
I'm closing this because the it has been successfully integrated with the described functionality. Thank you again for opening this for suggestion. 👍 🙏

**Comment by miurla** [comment]
Thanks for the quick response! I look forward to seeing it evolve further. 🚀 🚀
